import XCTest
@testable import SonarForge

final class AutoEQImporterTests: XCTestCase {

    /// Real-world shape: AutoEQ output for a typical headphone (10 filters,
    /// shelves at the extremes, mixed gains, preamp line).
    private let parametricSample = """
    Preamp: -6.8 dB
    Filter 1: ON LSC Fc 105 Hz Gain 6.5 dB Q 0.70
    Filter 2: ON PK Fc 162 Hz Gain -4.1 dB Q 0.71
    Filter 3: ON PK Fc 753 Hz Gain 2.5 dB Q 1.84
    Filter 4: ON PK Fc 1840 Hz Gain -3.7 dB Q 2.27
    Filter 5: ON PK Fc 3110 Hz Gain 4.9 dB Q 2.62
    Filter 6: ON PK Fc 5239 Hz Gain -4.2 dB Q 4.21
    Filter 7: ON PK Fc 6420 Hz Gain 3.2 dB Q 5.0
    Filter 8: ON PK Fc 8120 Hz Gain -2.8 dB Q 3.36
    Filter 9: ON PK Fc 9870 Hz Gain 1.9 dB Q 2.96
    Filter 10: ON HSC Fc 10000 Hz Gain -4.2 dB Q 0.70
    """

    func testParsesRealWorldParametricFile() throws {
        let result = try AutoEQImporter.parse(parametricSample)

        XCTAssertEqual(result.format, .parametric)
        XCTAssertEqual(result.bands.count, 10)
        XCTAssertEqual(result.preamp, -6.8, accuracy: 0.001)
        XCTAssertTrue(result.warnings.isEmpty)

        XCTAssertEqual(result.bands[0].type, .lowShelf)
        XCTAssertEqual(result.bands[0].frequency, 105, accuracy: 0.001)
        XCTAssertEqual(result.bands[0].gain, 6.5, accuracy: 0.001)
        XCTAssertEqual(result.bands[0].q, 0.70, accuracy: 0.001)

        XCTAssertEqual(result.bands[5].type, .peaking)
        XCTAssertEqual(result.bands[5].frequency, 5239, accuracy: 0.001)
        XCTAssertEqual(result.bands[5].gain, -4.2, accuracy: 0.001)

        XCTAssertEqual(result.bands[9].type, .highShelf)
    }

    func testSurvivesSurroundingProseAndBlankLines() throws {
        let noisy = """
        Sennheiser HD 600 — apply with any parametric EQ.

        \(parametricSample)

        Generated by AutoEq.
        """
        let result = try AutoEQImporter.parse(noisy)
        XCTAssertEqual(result.bands.count, 10)
        XCTAssertEqual(result.preamp, -6.8, accuracy: 0.001)
    }

    func testOffFiltersAreSkippedWithWarning() throws {
        let text = """
        Preamp: -2.0 dB
        Filter 1: ON PK Fc 100 Hz Gain 2.0 dB Q 1.0
        Filter 2: OFF PK Fc 200 Hz Gain 5.0 dB Q 1.0
        """
        let result = try AutoEQImporter.parse(text)
        XCTAssertEqual(result.bands.count, 1)
        XCTAssertTrue(result.warnings.contains(where: { $0.contains("OFF") }))
    }

    func testUnsupportedTypeWarnsAndContinues() throws {
        let text = """
        Filter 1: ON BP Fc 500 Hz Gain 1.0 dB Q 1.0
        Filter 2: ON PK Fc 1000 Hz Gain -2.0 dB Q 1.0
        """
        let result = try AutoEQImporter.parse(text)
        XCTAssertEqual(result.bands.count, 1)
        XCTAssertEqual(result.bands[0].type, .peaking)
        XCTAssertTrue(result.warnings.contains(where: { $0.contains("BP") }))
    }

    func testMissingQDefaultsToShelfConvention() throws {
        let text = "Filter 1: ON LS Fc 100 Hz Gain 3.0 dB"
        let result = try AutoEQImporter.parse(text)
        XCTAssertEqual(result.bands[0].q, 0.707, accuracy: 0.001)
        XCTAssertEqual(result.bands[0].type, .lowShelf)
    }

    func testMissingPreampDerivesHeadroomFromLargestBoost() throws {
        let text = """
        Filter 1: ON PK Fc 100 Hz Gain 5.5 dB Q 1.0
        Filter 2: ON PK Fc 1000 Hz Gain -3.0 dB Q 1.0
        """
        let result = try AutoEQImporter.parse(text)
        XCTAssertEqual(result.preamp, -5.5, accuracy: 0.001)
        XCTAssertTrue(result.warnings.contains(where: { $0.contains("Preamp") }))
    }

    func testMoreThanMaxBandsTruncatesWithWarning() throws {
        let lines = (1...20).map { "Filter \($0): ON PK Fc \($0 * 100) Hz Gain 1.0 dB Q 1.0" }
        let result = try AutoEQImporter.parse(lines.joined(separator: "\n"))
        XCTAssertEqual(result.bands.count, RealtimeParametricEQ.maxBands)
        XCTAssertTrue(result.warnings.contains(where: { $0.contains("16") }))
    }

    // MARK: - GraphicEQ

    func testGraphicEQReducesToBands() throws {
        // Synthetic curve: +6 dB bass shelf-ish, flat mids, -4 dB treble.
        var points: [String] = []
        for i in 0..<127 {
            let f = 20.0 * pow(10, Double(i) / 126.0 * 3.0)   // 20 Hz → 20 kHz log
            let gain: Double = f < 150 ? 6.0 : (f > 8000 ? -4.0 : 0.0)
            points.append("\(String(format: "%.1f", f)) \(String(format: "%.1f", gain))")
        }
        let result = try AutoEQImporter.parse("GraphicEQ: " + points.joined(separator: "; "))

        XCTAssertEqual(result.format, .graphic)
        XCTAssertFalse(result.bands.isEmpty)
        XCTAssertLessThanOrEqual(result.bands.count, AutoEQImporter.maxGraphicBands)
        XCTAssertEqual(result.preamp, -6.0, accuracy: 0.5, "headroom for the +6 dB region")

        // Low bands boosted, high bands cut, all peaking.
        let lowBands = result.bands.filter { $0.frequency < 120 }
        let highBands = result.bands.filter { $0.frequency > 10000 }
        XCTAssertFalse(lowBands.isEmpty)
        XCTAssertFalse(highBands.isEmpty)
        XCTAssertTrue(lowBands.allSatisfy { $0.gain > 4 })
        XCTAssertTrue(highBands.allSatisfy { $0.gain < -3 })
        XCTAssertTrue(result.bands.allSatisfy { $0.type == .peaking })
        XCTAssertTrue(result.warnings.contains(where: { $0.contains("approximated") }))
    }

    func testGraphicEQFlatRegionsProduceNoBands() throws {
        let flat = (0..<50).map { "\(20 + $0 * 400) 0.0" }.joined(separator: "; ")
        let result = try AutoEQImporter.parse("GraphicEQ: " + flat)
        XCTAssertTrue(result.bands.isEmpty, "near-zero gains are negligible — no bands needed")
    }

    // MARK: - Errors

    func testEmptyInputThrows() {
        XCTAssertThrowsError(try AutoEQImporter.parse("   \n  ")) { error in
            XCTAssertEqual(error as? AutoEQImporter.ImportError, .emptyInput)
        }
    }

    func testGarbageThrowsHelpfulError() {
        XCTAssertThrowsError(try AutoEQImporter.parse("hello world\nthis is not an eq file")) { error in
            XCTAssertEqual(error as? AutoEQImporter.ImportError, .noRecognizableContent)
            XCTAssertTrue((error.localizedDescription).contains("ParametricEQ.txt"))
        }
    }

    // MARK: - Round trip

    func testExportParseRoundTrip() throws {
        let original = try AutoEQImporter.parse(parametricSample)
        let text = AutoEQImporter.exportParametricText(preamp: original.preamp, bands: original.bands)
        let reparsed = try AutoEQImporter.parse(text)

        XCTAssertEqual(reparsed.preamp, original.preamp, accuracy: 0.01)
        XCTAssertEqual(reparsed.bands.count, original.bands.count)
        for (a, b) in zip(original.bands, reparsed.bands) {
            XCTAssertEqual(a.type, b.type)
            XCTAssertEqual(a.frequency, b.frequency, accuracy: 0.01)
            XCTAssertEqual(a.gain, b.gain, accuracy: 0.01)
            XCTAssertEqual(a.q, b.q, accuracy: 0.01)
        }
    }
}
